export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const EDIT_REQUEST = "EDIT_REQUEST"
export const EDIT_SUCCESS = "EDIT_SUCCESS"
export const EDIT_FAIL = "EDIT_FAIL"
export const EDIT_RESET = "EDIT_RESET"

export const RESETPW_REQUEST = "RESETPW_REQUEST"
export const RESETPW_SUCCESS = "RESETPW_SUCCESS"
export const RESETPW_FAIL = "RESETPW_FAIL"
export const RESETPW_RESET = "RESETPW_RESET"